# Generated by Django 3.0.6 on 2020-05-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/product/images/')),
                ('name', models.CharField(max_length=255)),
                ('sellable', models.BooleanField()),
                ('internal_reference', models.CharField(max_length=64)),
                ('barcode', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
