# Generated by Django 3.0.6 on 2020-05-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200507_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
