# Generated by Django 3.0.6 on 2020-05-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200507_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_sale_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='contents_qty',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
