# Generated by Django 3.0.6 on 2020-05-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200507_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_sale_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum sale quantity'),
        ),
    ]
