# Generated by Django 3.0.6 on 2020-05-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_code', models.CharField(max_length=64)),
                ('company_number', models.CharField(max_length=8)),
                ('website', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='uploads/partner/logos/')),
                ('ho_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
            ],
        ),
    ]
