# Generated by Django 3.0.6 on 2020-05-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='ho_address',
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='line1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='line2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='zip',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='partner',
            name='internal_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/partner/logos/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
