# Generated by Django 3.0.6 on 2020-05-06 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20200506_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=4)),
                ('job_position', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mobile_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('internal_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Line 2'),
        ),
    ]
