# Generated by Django 3.0.6 on 2020-05-06 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_address'),
        ('partners', '0005_contact_parent_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='zip',
        ),
        migrations.AddField(
            model_name='partner',
            name='hq_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
