# Generated by Django 3.0.6 on 2020-05-07 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_address'),
        ('partners', '0006_auto_20200506_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='hq_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address', verbose_name='HQ address'),
        ),
    ]
