# Generated by Django 3.0.6 on 2020-05-07 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200507_0018'),
        ('partners', '0008_auto_20200507_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='hq_address',
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
    ]
