# Generated by Django 3.0.6 on 2020-05-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200506_2153'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
