# Generated by Django 3.0.6 on 2020-05-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
